<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{

    public function run()
    {
        DB::table('cities')->insert([
            ['district_id' => 1, 'name' => 'Angoda'],
            ['district_id' => 1, 'name' => 'Athurugiriya'],
            ['district_id' => 1, 'name' => 'Avissawella'],
            ['district_id' => 1, 'name' => 'Bambalapitiya'],
            ['district_id' => 1, 'name' => 'Battaramulla'],
            ['district_id' => 1, 'name' => 'Bellanvila'],
            ['district_id' => 1, 'name' => 'Boralesgamuwa'],
            ['district_id' => 1, 'name' => 'Borella'],
            ['district_id' => 1, 'name' => 'Colombo 01'],
            ['district_id' => 1, 'name' => 'Colombo 02'],
            ['district_id' => 1, 'name' => 'Colombo 03'],
            ['district_id' => 1, 'name' => 'Colombo 04'],
            ['district_id' => 1, 'name' => 'Colombo 05'],
            ['district_id' => 1, 'name' => 'Colombo 06'],
            ['district_id' => 1, 'name' => 'Colombo 07'],
            ['district_id' => 1, 'name' => 'Colombo 08'],
            ['district_id' => 1, 'name' => 'Colombo 09'],
            ['district_id' => 1, 'name' => 'Colombo 10'],
            ['district_id' => 1, 'name' => 'Colombo 11'],
            ['district_id' => 1, 'name' => 'Colombo 12'],
            ['district_id' => 1, 'name' => 'Colombo 13'],
            ['district_id' => 1, 'name' => 'Colombo 14'],
            ['district_id' => 1, 'name' => 'Colombo 15'],
            ['district_id' => 1, 'name' => 'Dambahena'],
            ['district_id' => 1, 'name' => 'Dehiwala'],
            ['district_id' => 1, 'name' => 'Delkanda'],
            ['district_id' => 1, 'name' => 'Dematagoda'],
            ['district_id' => 1, 'name' => 'Galkissa'],
            ['district_id' => 1, 'name' => 'Godagama'],
            ['district_id' => 1, 'name' => 'Hanwella'],
            ['district_id' => 1, 'name' => 'Himbutana'],
            ['district_id' => 1, 'name' => 'Hokandara'],
            ['district_id' => 1, 'name' => 'Homagama'],
            ['district_id' => 1, 'name' => 'Kaduwela'],
            ['district_id' => 1, 'name' => 'Kahathuduwa'],
            ['district_id' => 1, 'name' => 'Kalubovila'],
            ['district_id' => 1, 'name' => 'Katukurunda'],
            ['district_id' => 1, 'name' => 'Kesbewa'],
            ['district_id' => 1, 'name' => 'Kirulapana'],
            ['district_id' => 1, 'name' => 'Kohuwala'],
            ['district_id' => 1, 'name' => 'Kollupitiya'],
            ['district_id' => 1, 'name' => 'Kolonnawa'],
            ['district_id' => 1, 'name' => 'Kosgama'],
            ['district_id' => 1, 'name' => 'Koswatta'],
            ['district_id' => 1, 'name' => 'Kotikawatta'],
            ['district_id' => 1, 'name' => 'Kottawa'],
            ['district_id' => 1, 'name' => 'Kotte'],
            ['district_id' => 1, 'name' => 'Maharagama'],
            ['district_id' => 1, 'name' => 'Malabe'],
            ['district_id' => 1, 'name' => 'Malagala'],
            ['district_id' => 1, 'name' => 'Meegoda'],
            ['district_id' => 1, 'name' => 'Moratuwa'],
            ['district_id' => 1, 'name' => 'Mulleriyawa'],
            ['district_id' => 1, 'name' => 'Narahenpita'],
            ['district_id' => 1, 'name' => 'Nawagamuwa'],
            ['district_id' => 1, 'name' => 'Nawala'],
            ['district_id' => 1, 'name' => 'Neelammahara'],
            ['district_id' => 1, 'name' => 'Nugegoda'],
            ['district_id' => 1, 'name' => 'Padukka'],
            ['district_id' => 1, 'name' => 'Panangoda'],
            ['district_id' => 1, 'name' => 'Pannipitiya'],
            ['district_id' => 1, 'name' => 'Pelawatta'],
            ['district_id' => 1, 'name' => 'Peliyagoda'],
            ['district_id' => 1, 'name' => 'Piliyandala'],
            ['district_id' => 1, 'name' => 'Pitakotte'],
            ['district_id' => 1, 'name' => 'Pitipana'],
            ['district_id' => 1, 'name' => 'Polgaovita'],
            ['district_id' => 1, 'name' => 'Puwakpitiya'],
            ['district_id' => 1, 'name' => 'Rajagiriya'],
            ['district_id' => 1, 'name' => 'Ranala'],
            ['district_id' => 1, 'name' => 'Ratmalana'],
            ['district_id' => 1, 'name' => 'Rukmalgama'],
            ['district_id' => 1, 'name' => 'Seethawaka'],
            ['district_id' => 1, 'name' => 'Thalawathugoda'],
            ['district_id' => 1, 'name' => 'Wathulla'],
            ['district_id' => 1, 'name' => 'Watareka'],
            ['district_id' => 1, 'name' => 'Welikada'],
            ['district_id' => 1, 'name' => 'Welisara'],
            ['district_id' => 1, 'name' => 'Wellampitiya'],

            ['district_id' => 2, 'name' => 'Aththanagalla'],
            ['district_id' => 2, 'name' => 'Badalgama'],
            ['district_id' => 2, 'name' => 'Balummahara'],
            ['district_id' => 2, 'name' => 'Biyagama'],
            ['district_id' => 2, 'name' => 'Biyanwila'],
            ['district_id' => 2, 'name' => 'Dadagamuwa'],
            ['district_id' => 2, 'name' => 'Danowita'],
            ['district_id' => 2, 'name' => 'Danwilana'],
            ['district_id' => 2, 'name' => 'Delgoda'],
            ['district_id' => 2, 'name' => 'Divulapitiya'],
            ['district_id' => 2, 'name' => 'Dompe'],
            ['district_id' => 2, 'name' => 'Ekala'],
            ['district_id' => 2, 'name' => 'Ellakkala'],
            ['district_id' => 2, 'name' => 'Galahitiyawa'],
            ['district_id' => 2, 'name' => 'Gampaha'],
            ['district_id' => 2, 'name' => 'Ganemulla'],
            ['district_id' => 2, 'name' => 'Gonawala'],
            ['district_id' => 2, 'name' => 'Hapugoda'],
            ['district_id' => 2, 'name' => 'Hendala'],
            ['district_id' => 2, 'name' => 'Hunupitiya'],
            ['district_id' => 2, 'name' => 'Ja-Ela'],
            ['district_id' => 2, 'name' => 'Kadawatha'],
            ['district_id' => 2, 'name' => 'Kalagedihena'],
            ['district_id' => 2, 'name' => 'Kamburugoda'],
            ['district_id' => 2, 'name' => 'Kandana'],
            ['district_id' => 2, 'name' => 'Katunayake'],
            ['district_id' => 2, 'name' => 'Kelaniya'],
            ['district_id' => 2, 'name' => 'Kendawala'],
            ['district_id' => 2, 'name' => 'Kindelpitiya'],
            ['district_id' => 2, 'name' => 'Kiribathgoda'],
            ['district_id' => 2, 'name' => 'Kirillawala'],
            ['district_id' => 2, 'name' => 'Kochchikade'],
            ['district_id' => 2, 'name' => 'Kotadeniyawa'],
            ['district_id' => 2, 'name' => 'Lansiyawadiya'],
            ['district_id' => 2, 'name' => 'Makola'],
            ['district_id' => 2, 'name' => 'Minuwangoda'],
            ['district_id' => 2, 'name' => 'Mirigama'],
            ['district_id' => 2, 'name' => 'Mugurugampala'],
            ['district_id' => 2, 'name' => 'Negombo'],
            ['district_id' => 2, 'name' => 'Nittambuwa'],
            ['district_id' => 2, 'name' => 'Ovitigama'],
            ['district_id' => 2, 'name' => 'Pamunugama'],
            ['district_id' => 2, 'name' => 'Pasyala'],
            ['district_id' => 2, 'name' => 'Peralanda'],
            ['district_id' => 2, 'name' => 'Pugoda'],
            ['district_id' => 2, 'name' => 'Raddelgoda'],
            ['district_id' => 2, 'name' => 'Ragama'],
            ['district_id' => 2, 'name' => 'Sapugaskanda'],
            ['district_id' => 2, 'name' => 'Seeduwa'],
            ['district_id' => 2, 'name' => 'Sinharamulla'],
            ['district_id' => 2, 'name' => 'Siyambalape'],
            ['district_id' => 2, 'name' => 'Thalgasmote'],
            ['district_id' => 2, 'name' => 'Udugampola'],
            ['district_id' => 2, 'name' => 'Uswetakeiyawa'],
            ['district_id' => 2, 'name' => 'Veyangoda'],
            ['district_id' => 2, 'name' => 'Wattala'],
            ['district_id' => 2, 'name' => 'Weliweriya'],
            ['district_id' => 2, 'name' => 'Wetakeyawa'],
            ['district_id' => 2, 'name' => 'Yakkala'],

            ['district_id' => 3, 'name' => 'Akurana'],
            ['district_id' => 3, 'name' => 'Ampitiya'],
            ['district_id' => 3, 'name' => 'Digana'],
            ['district_id' => 3, 'name' => 'Galagedara'],
            ['district_id' => 3, 'name' => 'Gampola'],
            ['district_id' => 3, 'name' => 'Gelioya'],
            ['district_id' => 3, 'name' => 'Hanguranketha'],
            ['district_id' => 3, 'name' => 'Harispattuwa'],
            ['district_id' => 3, 'name' => 'Kadugannawa'],
            ['district_id' => 3, 'name' => 'Kandy'],
            ['district_id' => 3, 'name' => 'Katugastota'],
            ['district_id' => 3, 'name' => 'Kundasale'],
            ['district_id' => 3, 'name' => 'Madawala Bazaar'],
            ['district_id' => 3, 'name' => 'Menikhinna'],
            ['district_id' => 3, 'name' => 'Nawalapitiya'],
            ['district_id' => 3, 'name' => 'Peradeniya'],
            ['district_id' => 3, 'name' => 'Pilimatalawa'],
            ['district_id' => 3, 'name' => 'Teldeniya'],
            ['district_id' => 3, 'name' => 'Thalathuoya'],
            ['district_id' => 3, 'name' => 'Uduwela'],
            ['district_id' => 3, 'name' => 'Urapola'],
            ['district_id' => 3, 'name' => 'Wattegama'],

            ['district_id' => 4, 'name' => 'Alawwa'],
            ['district_id' => 4, 'name' => 'Ambanpola'],
            ['district_id' => 4, 'name' => 'Bingiriya'],
            ['district_id' => 4, 'name' => 'Dambadeniya'],
            ['district_id' => 4, 'name' => 'Esseddawa'],
            ['district_id' => 4, 'name' => 'Galgamuwa'],
            ['district_id' => 4, 'name' => 'Giriulla'],
            ['district_id' => 4, 'name' => 'Hettipola'],
            ['district_id' => 4, 'name' => 'Ibbagamuwa'],
            ['district_id' => 4, 'name' => 'Kuliyapitiya'],
            ['district_id' => 4, 'name' => 'Kurunegala'],
            ['district_id' => 4, 'name' => 'Mawathagama'],
            ['district_id' => 4, 'name' => 'Meegahakotuwa'],
            ['district_id' => 4, 'name' => 'Narammala'],
            ['district_id' => 4, 'name' => 'Nikaweratiya'],
            ['district_id' => 4, 'name' => 'Pannala'],
            ['district_id' => 4, 'name' => 'Polgahawela'],
            ['district_id' => 4, 'name' => 'Thulhiriya'],
            ['district_id' => 4, 'name' => 'Wariyapola'],
            ['district_id' => 4, 'name' => 'Yanthampalawa'],
            ['district_id' => 4, 'name' => 'Yapahuwa'],

            ['district_id' => 5, 'name' => 'Aluthgama'],
            ['district_id' => 5, 'name' => 'Bandaragama'],
            ['district_id' => 5, 'name' => 'Beruwala'],
            ['district_id' => 5, 'name' => 'Bulathsinhala'],
            ['district_id' => 5, 'name' => 'Horana'],
            ['district_id' => 5, 'name' => 'Ingiriya'],
            ['district_id' => 5, 'name' => 'Ittapana'],
            ['district_id' => 5, 'name' => 'Kalutara'],
            ['district_id' => 5, 'name' => 'Mathugama'],
            ['district_id' => 5, 'name' => 'Mattegoda'],
            ['district_id' => 5, 'name' => 'Matugama'],
            ['district_id' => 5, 'name' => 'Pahiyangala'],
            ['district_id' => 5, 'name' => 'Panadura'],
            ['district_id' => 5, 'name' => 'Payagala'],
            ['district_id' => 5, 'name' => 'Wadduwa'],

            ['district_id' => 6, 'name' => 'Ahangama'],
            ['district_id' => 6, 'name' => 'Ahungalla'],
            ['district_id' => 6, 'name' => 'Ambalangoda'],
            ['district_id' => 6, 'name' => 'Baddegama'],
            ['district_id' => 6, 'name' => 'Balapitiya'],
            ['district_id' => 6, 'name' => 'Batapola'],
            ['district_id' => 6, 'name' => 'Bentota'],
            ['district_id' => 6, 'name' => 'Delkabalagoda'],
            ['district_id' => 6, 'name' => 'Elpitiya'],
            ['district_id' => 6, 'name' => 'Galle'],
            ['district_id' => 6, 'name' => 'Gonapinuwala'],
            ['district_id' => 6, 'name' => 'Habaraduwa'],
            ['district_id' => 6, 'name' => 'Hikkaduwa'],
            ['district_id' => 6, 'name' => 'Hiniduma'],
            ['district_id' => 6, 'name' => 'Imaduwa'],
            ['district_id' => 6, 'name' => 'Karandeniya'],
            ['district_id' => 6, 'name' => 'Karapitiya'],
            ['district_id' => 6, 'name' => 'Koggala'],
            ['district_id' => 6, 'name' => 'Kosgoda'],
            ['district_id' => 6, 'name' => 'Mapalagama'],
            ['district_id' => 6, 'name' => 'Massalgoda'],
            ['district_id' => 6, 'name' => 'Meetiyagoda'],
            ['district_id' => 6, 'name' => 'Nagoda'],
            ['district_id' => 6, 'name' => 'Neluwa'],
            ['district_id' => 6, 'name' => 'Pitigala'],
            ['district_id' => 6, 'name' => 'Poddala'],
            ['district_id' => 6, 'name' => 'Thawalama'],
            ['district_id' => 6, 'name' => 'Udugama'],
            ['district_id' => 6, 'name' => 'Unawatuna'],
            ['district_id' => 6, 'name' => 'Wanduramba'],
            ['district_id' => 6, 'name' => 'Wenamulla'],
            ['district_id' => 6, 'name' => 'Yakkalamulla'],

            ['district_id' => 7, 'name' => 'Ayagama'],
            ['district_id' => 7, 'name' => 'Balangoda'],
            ['district_id' => 7, 'name' => 'Eheliyagoda'],
            ['district_id' => 7, 'name' => 'Elapatha'],
            ['district_id' => 7, 'name' => 'Embilipitiya'],
            ['district_id' => 7, 'name' => 'Godakawela'],
            ['district_id' => 7, 'name' => 'Imbulpe'],
            ['district_id' => 7, 'name' => 'Ihalagama'],
            ['district_id' => 7, 'name' => 'Kahawatta'],
            ['district_id' => 7, 'name' => 'Kalawana'],
            ['district_id' => 7, 'name' => 'Kolonne'],
            ['district_id' => 7, 'name' => 'Kuruwita'],
            ['district_id' => 7, 'name' => 'Nivitigala'],
            ['district_id' => 7, 'name' => 'Opanayaka'],
            ['district_id' => 7, 'name' => 'Panamure'],
            ['district_id' => 7, 'name' => 'Pelmadulla'],
            ['district_id' => 7, 'name' => 'Pohorabawa'],
            ['district_id' => 7, 'name' => 'Pothupitiya'],
            ['district_id' => 7, 'name' => 'Rakwana'],
            ['district_id' => 7, 'name' => 'Ratnapura'],
            ['district_id' => 7, 'name' => 'Weligepola'],
            ['district_id' => 7, 'name' => 'Weralupa'],

            ['district_id' => 8, 'name' => 'Akuressa'],
            ['district_id' => 8, 'name' => 'Aparekka'],
            ['district_id' => 8, 'name' => 'Denipitiya'],
            ['district_id' => 8, 'name' => 'Deniyaya'],
            ['district_id' => 8, 'name' => 'Devinuwara'],
            ['district_id' => 8, 'name' => 'Dikwella'],
            ['district_id' => 8, 'name' => 'Gandara'],
            ['district_id' => 8, 'name' => 'Hakmana'],
            ['district_id' => 8, 'name' => 'Kamburugamuwa'],
            ['district_id' => 8, 'name' => 'Kamburupitiya'],
            ['district_id' => 8, 'name' => 'Karaputugala'],
            ['district_id' => 8, 'name' => 'Kekanadurra'],
            ['district_id' => 8, 'name' => 'Malimbada'],
            ['district_id' => 8, 'name' => 'Matara'],
            ['district_id' => 8, 'name' => 'Midigama'],
            ['district_id' => 8, 'name' => 'Mirissa'],
            ['district_id' => 8, 'name' => 'Morawaka'],
            ['district_id' => 8, 'name' => 'Muruthamuraya'],
            ['district_id' => 8, 'name' => 'Pitabeddara'],
            ['district_id' => 8, 'name' => 'Thelijjawila'],
            ['district_id' => 8, 'name' => 'Tihagoda'],
            ['district_id' => 8, 'name' => 'Urubokka'],
            ['district_id' => 8, 'name' => 'Weligama'],
            ['district_id' => 8, 'name' => 'Welipitiya'],

            ['district_id' => 9, 'name' => 'Anuradhapura'],
            ['district_id' => 9, 'name' => 'Bulnewa'],
            ['district_id' => 9, 'name' => 'Eppawala'],
            ['district_id' => 9, 'name' => 'Galenbindunuwewa'],
            ['district_id' => 9, 'name' => 'Galnewa'],
            ['district_id' => 9, 'name' => 'Ganewalpola'],
            ['district_id' => 9, 'name' => 'Habarana'],
            ['district_id' => 9, 'name' => 'Herathhalmillewa'],
            ['district_id' => 9, 'name' => 'Horowupotana'],
            ['district_id' => 9, 'name' => 'Kahatagasdigiliya'],
            ['district_id' => 9, 'name' => 'Kebitigollawa'],
            ['district_id' => 9, 'name' => 'Kekirawa'],
            ['district_id' => 9, 'name' => 'Konapathirawa'],
            ['district_id' => 9, 'name' => 'Konwewa'],
            ['district_id' => 9, 'name' => 'Madatugama'],
            ['district_id' => 9, 'name' => 'Medawachchiya'],
            ['district_id' => 9, 'name' => 'Mahailuppallama'],
            ['district_id' => 9, 'name' => 'Maradankadawala'],
            ['district_id' => 9, 'name' => 'Mihintale'],
            ['district_id' => 9, 'name' => 'Nochchiyagama'],
            ['district_id' => 9, 'name' => 'Padaviya'],
            ['district_id' => 9, 'name' => 'Palugaswewa'],
            ['district_id' => 9, 'name' => 'Rajangana'],
            ['district_id' => 9, 'name' => 'Rambewa'],
            ['district_id' => 9, 'name' => 'Seeppukulama'],
            ['district_id' => 9, 'name' => 'Talawa'],
            ['district_id' => 9, 'name' => 'Tambuttegama'],
            ['district_id' => 9, 'name' => 'Thirappane'],
            ['district_id' => 9, 'name' => 'Yakalla'],

            ['district_id' => 10, 'name' => 'Anamaduwa'],
            ['district_id' => 10, 'name' => 'Battuluoya'],
            ['district_id' => 10, 'name' => 'Chilaw'],
            ['district_id' => 10, 'name' => 'Dankotuwa'],
            ['district_id' => 10, 'name' => 'Eluvankulam'],
            ['district_id' => 10, 'name' => 'Kalpitiya'],
            ['district_id' => 10, 'name' => 'Madampe'],
            ['district_id' => 10, 'name' => 'Mahawewa'],
            ['district_id' => 10, 'name' => 'Marawila'],
            ['district_id' => 10, 'name' => 'Mundel'],
            ['district_id' => 10, 'name' => 'Nattandiya'],
            ['district_id' => 10, 'name' => 'Nuraicholai'],
            ['district_id' => 10, 'name' => 'Palavi'],
            ['district_id' => 10, 'name' => 'Puttalama'],
            ['district_id' => 10, 'name' => 'Thillayadi'],
            ['district_id' => 10, 'name' => 'Wanathawilluwa'],
            ['district_id' => 10, 'name' => 'Wennappuwa'],

            ['district_id' => 11, 'name' => 'Ambepussa'],
            ['district_id' => 11, 'name' => 'Amithirigala'],
            ['district_id' => 11, 'name' => 'Aranayaka'],
            ['district_id' => 11, 'name' => 'Bakmeedeniya'],
            ['district_id' => 11, 'name' => 'Bulathkohupitiya'],
            ['district_id' => 11, 'name' => 'Dehiowita'],
            ['district_id' => 11, 'name' => 'Deraniyagala'],
            ['district_id' => 11, 'name' => 'Dodanthale'],
            ['district_id' => 11, 'name' => 'Eriyawa'],
            ['district_id' => 11, 'name' => 'Galigamuwa'],
            ['district_id' => 11, 'name' => 'Ganithapura'],
            ['district_id' => 11, 'name' => 'Hemmathagama'],
            ['district_id' => 11, 'name' => 'Karawanella'],
            ['district_id' => 11, 'name' => 'Kegalle'],
            ['district_id' => 11, 'name' => 'Kiringadeniya'],
            ['district_id' => 11, 'name' => 'Kitulgala'],
            ['district_id' => 11, 'name' => 'Kotiyakumbura'],
            ['district_id' => 11, 'name' => 'Mawanella'],
            ['district_id' => 11, 'name' => 'Pinnawala'],
            ['district_id' => 11, 'name' => 'Rambukkana'],
            ['district_id' => 11, 'name' => 'Ruwanwella'],
            ['district_id' => 11, 'name' => 'Thalgaspitiya'],
            ['district_id' => 11, 'name' => 'Warakapola'],
            ['district_id' => 11, 'name' => 'Yatiyantota'],

            ['district_id' => 12, 'name' => 'Chavakachcheri'],
            ['district_id' => 12, 'name' => 'Chankanai'],
            ['district_id' => 12, 'name' => 'Jaffna'],
            ['district_id' => 12, 'name' => 'Karainagar'],
            ['district_id' => 12, 'name' => 'Karaveddy'],
            ['district_id' => 12, 'name' => 'Kayts'],
            ['district_id' => 12, 'name' => 'Kopay'],
            ['district_id' => 12, 'name' => 'Maruthankerney'],
            ['district_id' => 12, 'name' => 'Nallur'],
            ['district_id' => 12, 'name' => 'Point Pedro'],
            ['district_id' => 12, 'name' => 'Sandilipay'],
            ['district_id' => 12, 'name' => 'Tellippalai'],
            ['district_id' => 12, 'name' => 'Uduvil'],
            ['district_id' => 12, 'name' => 'Velanai'],

            ['district_id' => 13, 'name' => 'Badulla'],
            ['district_id' => 13, 'name' => 'Beragala'],
            ['district_id' => 13, 'name' => 'Bandarawela'],
            ['district_id' => 13, 'name' => 'Diyatalawa'],
            ['district_id' => 13, 'name' => 'Ella'],
            ['district_id' => 13, 'name' => 'Girandurukotte'],
            ['district_id' => 13, 'name' => 'Haldummulla'],
            ['district_id' => 13, 'name' => 'Hali Ela'],
            ['district_id' => 13, 'name' => 'Haputale'],
            ['district_id' => 13, 'name' => 'Kahagolla'],
            ['district_id' => 13, 'name' => 'Kandaketiya'],
            ['district_id' => 13, 'name' => 'Lunugala'],
            ['district_id' => 13, 'name' => 'Mahiyanganaya'],
            ['district_id' => 13, 'name' => 'Meegahakivula'],
            ['district_id' => 13, 'name' => 'Paranagama'],
            ['district_id' => 13, 'name' => 'Passara'],
            ['district_id' => 13, 'name' => 'Tennapanguwa'],
            ['district_id' => 13, 'name' => 'Welimada'],

            ['district_id' => 14, 'name' => 'Addalaichchenai'],
            ['district_id' => 14, 'name' => 'Akkaraipattu'],
            ['district_id' => 14, 'name' => 'Alayadivembu'],
            ['district_id' => 14, 'name' => 'Ampara'],
            ['district_id' => 14, 'name' => 'Damana'],
            ['district_id' => 14, 'name' => 'Dehiattakandiya'],
            ['district_id' => 14, 'name' => 'Hingurana'],
            ['district_id' => 14, 'name' => 'Irakkamam'],
            ['district_id' => 14, 'name' => 'Kalmunai'],
            ['district_id' => 14, 'name' => 'Karaitivu'],
            ['district_id' => 14, 'name' => 'Kirindiwela'],
            ['district_id' => 14, 'name' => 'Lahugala'],
            ['district_id' => 14, 'name' => 'Maha Oya'],
            ['district_id' => 14, 'name' => 'Navithanveli'],
            ['district_id' => 14, 'name' => 'Nintavur'],
            ['district_id' => 14, 'name' => 'Padiyathalawa'],
            ['district_id' => 14, 'name' => 'Pottuvil'],
            ['district_id' => 14, 'name' => 'Sainthamaruthu'],
            ['district_id' => 14, 'name' => 'Sammanthurai'],
            ['district_id' => 14, 'name' => 'Thirukkovil'],
            ['district_id' => 14, 'name' => 'Uhana'],

            ['district_id' => 15, 'name' => 'Angunukolapelessa'],
            ['district_id' => 15, 'name' => 'Ambalantota'],
            ['district_id' => 15, 'name' => 'Beliatta'],
            ['district_id' => 15, 'name' => 'Hambantota'],
            ['district_id' => 15, 'name' => 'Lunugamwehera'],
            ['district_id' => 15, 'name' => 'Middeniya'],
            ['district_id' => 15, 'name' => 'Tangalle'],
            ['district_id' => 15, 'name' => 'Tissamaharama'],
            ['district_id' => 15, 'name' => 'Udawalawa'],
            ['district_id' => 15, 'name' => 'Walasmulla'],
            ['district_id' => 15, 'name' => 'Weerawila'],

            ['district_id' => 16, 'name' => 'Araiyampathy'],
            ['district_id' => 16, 'name' => 'Batticaloa'],
            ['district_id' => 16, 'name' => 'Chenkalady'],
            ['district_id' => 16, 'name' => 'Eravur'],
            ['district_id' => 16, 'name' => 'Kaluvanchikudy'],
            ['district_id' => 16, 'name' => 'Kattankudy'],
            ['district_id' => 16, 'name' => 'Kiran'],
            ['district_id' => 16, 'name' => 'Kokkadichcholai'],
            ['district_id' => 16, 'name' => 'Oddamavadi'],
            ['district_id' => 16, 'name' => 'Pasikudah'],
            ['district_id' => 16, 'name' => 'Vakarai'],
            ['district_id' => 16, 'name' => 'Valaichchenai'],
            ['district_id' => 16, 'name' => 'Vavunathivu'],
            ['district_id' => 16, 'name' => 'Vellavely'],

            ['district_id' => 17, 'name' => 'Agalawatta'],
            ['district_id' => 17, 'name' => 'Dambulla'],
            ['district_id' => 17, 'name' => 'Elkaduwa'],
            ['district_id' => 17, 'name' => 'Galewela'],
            ['district_id' => 17, 'name' => 'Gammaduwa'],
            ['district_id' => 17, 'name' => 'Inamaluwa'],
            ['district_id' => 17, 'name' => 'Kaikawala'],
            ['district_id' => 17, 'name' => 'Kibissa'],
            ['district_id' => 17, 'name' => 'Laggala Pallegama'],
            ['district_id' => 17, 'name' => 'Madawala Ulpotha'],
            ['district_id' => 17, 'name' => 'Matale'],
            ['district_id' => 17, 'name' => 'Nalanda'],
            ['district_id' => 17, 'name' => 'Naula'],
            ['district_id' => 17, 'name' => 'Palapathwela'],
            ['district_id' => 17, 'name' => 'Pallepola'],
            ['district_id' => 17, 'name' => 'Rattota'],
            ['district_id' => 17, 'name' => 'Sigiriya'],
            ['district_id' => 17, 'name' => 'Ukuwela'],
            ['district_id' => 17, 'name' => 'Uyanwatta'],
            ['district_id' => 17, 'name' => 'Wahacotte'],
            ['district_id' => 17, 'name' => 'Walliwela'],
            ['district_id' => 17, 'name' => 'Yatawatta'],

            ['district_id' => 18, 'name' => 'Gomarankadawala'],
            ['district_id' => 18, 'name' => 'Kantale'],
            ['district_id' => 18, 'name' => 'Kinniya'],
            ['district_id' => 18, 'name' => 'Kuchchaveli'],
            ['district_id' => 18, 'name' => 'Morawewa'],
            ['district_id' => 18, 'name' => 'Muttur'],
            ['district_id' => 18, 'name' => 'Siripura'],
            ['district_id' => 18, 'name' => 'Seruvila'],
            ['district_id' => 18, 'name' => 'Thampalakamam'],
            ['district_id' => 18, 'name' => 'Trincomalee'],
            ['district_id' => 18, 'name' => 'Verugal'],

            ['district_id' => 19, 'name' => 'Badalkumbura'],
            ['district_id' => 19, 'name' => 'Bibile'],
            ['district_id' => 19, 'name' => 'Buttala'],
            ['district_id' => 19, 'name' => 'Kataragama'],
            ['district_id' => 19, 'name' => 'Madulla'],
            ['district_id' => 19, 'name' => 'Medagama'],
            ['district_id' => 19, 'name' => 'Moneragala'],
            ['district_id' => 19, 'name' => 'Nakkala'],
            ['district_id' => 19, 'name' => 'Okkampitiya'],
            ['district_id' => 19, 'name' => 'Siyambalanduwa'],
            ['district_id' => 19, 'name' => 'Thanamalwila'],
            ['district_id' => 19, 'name' => 'Wellawaya'],

            ['district_id' => 20, 'name' => 'Aralaganwila'],
            ['district_id' => 20, 'name' => 'Bakamuna'],
            ['district_id' => 20, 'name' => 'Dimbulagala'],
            ['district_id' => 20, 'name' => 'Elahera'],
            ['district_id' => 20, 'name' => 'Galamuna'],
            ['district_id' => 20, 'name' => 'Giritale'],
            ['district_id' => 20, 'name' => 'Hingurakgoda'],
            ['district_id' => 20, 'name' => 'Jayantipura'],
            ['district_id' => 20, 'name' => 'Kaduruwela'],
            ['district_id' => 20, 'name' => 'Lankapura'],
            ['district_id' => 20, 'name' => 'Manampitiya'],
            ['district_id' => 20, 'name' => 'Medirigiriya'],
            ['district_id' => 20, 'name' => 'Minneriya'],
            ['district_id' => 20, 'name' => 'Polonnaruwa'],
            ['district_id' => 20, 'name' => 'Sungawila'],
            ['district_id' => 20, 'name' => 'Welikanda'],

            ['district_id' => 21, 'name' => 'Ambewela'],
            ['district_id' => 21, 'name' => 'Agrapatana'],
            ['district_id' => 21, 'name' => 'Bogawantalawa'],
            ['district_id' => 21, 'name' => 'Bopattalawa'],
            ['district_id' => 21, 'name' => 'Dayagama Bazaar'],
            ['district_id' => 21, 'name' => 'Ginigathhena'],
            ['district_id' => 21, 'name' => 'Haggala'],
            ['district_id' => 21, 'name' => 'Hatton'],
            ['district_id' => 21, 'name' => 'Hapugastalawa'],
            ['district_id' => 21, 'name' => 'Kandapola'],
            ['district_id' => 21, 'name' => 'Kotagala'],
            ['district_id' => 21, 'name' => 'Koththallena'],
            ['district_id' => 21, 'name' => 'Kotmale'],
            ['district_id' => 21, 'name' => 'Labukele'],
            ['district_id' => 21, 'name' => 'Laxapana'],
            ['district_id' => 21, 'name' => 'Maskeliya'],
            ['district_id' => 21, 'name' => 'Nanu Oya'],
            ['district_id' => 21, 'name' => 'Nildandahinna'],
            ['district_id' => 21, 'name' => 'Norton'],
            ['district_id' => 21, 'name' => 'Nuwara Eliya'],
            ['district_id' => 21, 'name' => 'Padiyapelella'],
            ['district_id' => 21, 'name' => 'Pattipola'],
            ['district_id' => 21, 'name' => 'Pundaluoya'],
            ['district_id' => 21, 'name' => 'Ramboda'],
            ['district_id' => 21, 'name' => 'Ragala'],
            ['district_id' => 21, 'name' => 'Rozella'],
            ['district_id' => 21, 'name' => 'Talawakelle'],
            ['district_id' => 21, 'name' => 'Udapussallawa'],
            ['district_id' => 21, 'name' => 'Walapane'],
            ['district_id' => 21, 'name' => 'Watawala'],

            ['district_id' => 22, 'name' => 'Cheddikulam'],
            ['district_id' => 22, 'name' => 'Nedunkeni'],
            ['district_id' => 22, 'name' => 'Vavuniya'],

            ['district_id' => 23, 'name' => 'Kandavalai'],
            ['district_id' => 23, 'name' => 'Kilinochchi'],
            ['district_id' => 23, 'name' => 'Pallai'],
            ['district_id' => 23, 'name' => 'Poonakary'],

            ['district_id' => 24, 'name' => 'Adampan'],
            ['district_id' => 24, 'name' => 'Chilawathurai'],
            ['district_id' => 24, 'name' => 'Madhu'],
            ['district_id' => 24, 'name' => 'Mannar'],
            ['district_id' => 24, 'name' => 'Nanaddan'],

            ['district_id' => 25, 'name' => 'Pandiyankulam'],
            ['district_id' => 25, 'name' => 'Mullaitivu'],
            ['district_id' => 25, 'name' => 'Oddusuddan'],
            ['district_id' => 25, 'name' => 'Puthukkudiyiruppu'],
            ['district_id' => 25, 'name' => 'Thunukkai'],
            ['district_id' => 25, 'name' => 'Ehatugaswewa']
        ]);
    }
}
